output_dir: {{ output_path }}
checkpoint: {{ checkpoint }}

dataset:
  class: {{ dataset }} # BinaryLocalization / SubcellularLocalization
  path: #
  atom_feature: null
  bond_feature: null
  transform:
    class: Compose
    transforms:
      - class: ProteinView
        view: "residue"

task:
  class: PropertyPrediction
  model:
    class: PretrainESM
    path: #
    model: ESM-2-650M
    mask_modeling: False
    output_dim: 512
    readout: pooler
    use_proj: True
  criterion: ce
  metric: ["acc", "mcc"]
  num_mlp_layer: 2
  num_class: {{ num_class }}

eval_metric: accuracy

optimizer:
  class: Adam
  lr: 0.00005

fix_encoder: True

engine:
  gpus: [0, 1, 2, 3]
  batch_size: {{ batch_size }} # td_datasets.Thermostability: 8; others: 32

train:
  num_epoch: 100
