output_dir: {{ output_path }}
checkpoint: {{ checkpoint }}

dataset:
  class: {{ dataset }} # td_datasets.EnzymeCommission / GeneOntology
  path: #
  branch: {{ branch }} # EC: null; GO_MF: MF; GO_CC: CC; GO_BP: BP
  test_cutoff: 0.95
  atom_feature: null
  bond_feature: null
  transform:
    class: Compose
    transforms:
      - class: ProteinView
        view: residue
      - class: TruncateProtein
        max_length: 550

task:
  class: MultipleBinaryClassification
  model:
    class: PretrainProtBert
    path: #
    mask_modeling: False
    output_dim: 512
    readout: pooler
    use_proj: False
  criterion: bce
  metric: ['auprc@micro', 'f1_max']
  num_mlp_layer: 2

optimizer:
  class: Adam
  lr: {{ learning_rate }}

engine:
  gpus: [0, 1, 2, 3]
  batch_size: {{ batch_size }}
  log_interval: 1000

lr_ratio: 0.05

eval_metric: f1_max

train:
  num_epoch: 50

# test_batch_size: {{ batch_size }}