output_dir: {{ output_path }}
checkpoint: {{ checkpoint }}

dataset:
  class: {{ dataset }} # BetaLactamase / Fluorescence / Stability / td_datasets.AAV
  path: #
  atom_feature: null
  bond_feature: null
  transform:
    class: Compose
    transforms:
      - class: ProteinView
        view: "residue"

task:
  class: PropertyPrediction
  model:
    class: PretrainProtBert
    path: #
    mask_modeling: False
    output_dim: 512
    readout: pooler
    use_proj: True
  criterion: mse
  metric: ["mae", "rmse", "spearmanr"]
  normalization: False
  num_mlp_layer: 2

eval_metric: spearmanr

optimizer:
  class: Adam
  lr: {{ learning_rate }}

lr_ratio: 0.02

engine:
  gpus: [0, 1, 2, 3]
  batch_size: {{ batch_size }}

train:
  num_epoch: 100

# test_batch_size: {{ batch_size }}