batch_size: 2

queue_size: 13200
#queue_size: 4800
alpha: 0.4

freeze_text: true
freeze_seq: false

# optimizer
weight_decay: 0
init_lr: 3e-5
max_epoch: 20

match: 'none'
dataset: 'domain'
corrupt_strategy: 'none'

name: '13200_protst_lower_case_2layer_2e-5_protbert_bfd_2e-6_fix_text_with_itm_ddp2*8_bf16'