batch_size: 2

queue_size: 16384
#queue_size: 4800
alpha: 0.4

freeze_text: true
freeze_seq: false

# optimizer
weight_decay: 0
init_lr: 3e-5
max_epoch: 20

model: 'esm2'
seq_config: 'configs/encoder2.json'

match: 'none'
dataset: 'domain'
corrupt_strategy: 'none'

name: 'esm2_test_16384_protst_lower_case_2layer_2e-5_2e-6_fix_text_with_itm_ddp2*8_bf16'